HF_TOKEN = "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"

GROQ_API_KEY = "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"

TAVILY_API_KEY = "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"

SERPER_API_KEY = "0db10ff4e3cae3b12a39488f8c9aab431752f769"